import type { Product } from "../types/product";

export const mockProducts: Product[] = [
    {
        id: "1",
        name: "Classic Sneakers",
        description: "Comfortable and stylish sneakers for everyday wear.",
        price: 89.99,
        category: "Footwear",
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=60",
        stock: 25,
        rating: 4.5,
        numReviews: 120,
    },
    {
        id: "2",
        name: "Wireless Headphones",
        description: "Noise-canceling headphones with premium sound quality.",
        price: 199.99,
        category: "Electronics",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=60",
        stock: 15,
        rating: 4.8,
        numReviews: 85,
    },
    {
        id: "3",
        name: "Smart Watch",
        description: "Track your fitness and stay connected with this smart watch.",
        price: 249.99,
        category: "Electronics",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=60",
        stock: 10,
        rating: 4.2,
        numReviews: 45,
    },
    {
        id: "4",
        name: "Leather Backpack",
        description: "Durable and elegant leather backpack for work and travel.",
        price: 129.99,
        category: "Accessories",
        image: "https://images.unsplash.com/photo-1548036654-3c66a7196603?w=600&auto=format&fit=crop&q=60",
        stock: 20,
        rating: 4.7,
        numReviews: 60,
    },
    {
        id: "5",
        name: "Minimalist Watch",
        description: "A clean and simple watch for a modern look.",
        price: 159.99,
        category: "Accessories",
        image: "https://images.unsplash.com/photo-1524805444758-09919d38ae09?w=600&auto=format&fit=crop&q=60",
        stock: 30,
        rating: 4.6,
        numReviews: 32,
    },
    {
        id: "6",
        name: "Graphic T-Shirt",
        description: "Soft cotton t-shirt with a unique graphic design.",
        price: 29.99,
        category: "Apparel",
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format&fit=crop&q=60",
        stock: 50,
        rating: 4.4,
        numReviews: 95,
    },
];
